# Generated by Django 4.2.5 on 2023-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tpinjaman',
            fields=[
                ('No_Rek_Pinjaman', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('No_Rek_Tabungan', models.CharField(max_length=16)),
                ('Jenis_Pinjaman', models.CharField(max_length=255)),
                ('Kode_Anggota', models.CharField(max_length=7)),
                ('Tanggal_Akad_Peminjaman', models.DateField()),
                ('Prosentase_Bunga', models.CharField(max_length=255)),
                ('Jumlah_Pinjaman', models.CharField(max_length=100)),
                ('Biaya_Administrasi', models.CharField(max_length=50)),
                ('Tabungan_Wajib', models.CharField(max_length=100)),
                ('Jumlah_Angsuran', models.CharField(max_length=100)),
                ('Angsuran_Perbulan', models.CharField(max_length=255)),
                ('Bulan_Mulai_Angsuran', models.DateField()),
                ('Tanggal_Angsuran_Perbulan', models.DateField()),
            ],
            options={
                'db_table': 'tblPinjaman',
            },
        ),
    ]
