# Generated by Django 4.2.5 on 2023-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAnggota',
            fields=[
                ('kode_Anggota', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('Nama_Anggota', models.CharField(max_length=255)),
                ('Nomor_Induk_Kependudukan', models.IntegerField(max_length=16)),
                ('Tgl_Lahir', models.DateField()),
                ('Agama', models.CharField(max_length=15)),
                ('No_Hp', models.IntegerField(max_length=12)),
                ('No_Telp_Rumah', models.IntegerField(max_length=12)),
                ('Pekerjaan', models.CharField(max_length=255)),
                ('Alamat', models.CharField(max_length=552)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'tblAnggota',
            },
        ),
    ]
