# Generated by Django 4.2.5 on 2023-11-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manggota',
            name='No_Hp',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='manggota',
            name='No_Telp_Rumah',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='manggota',
            name='Nomor_Induk_Kependudukan',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='manggota',
            name='kode_Anggota',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
