# Generated by Django 4.2.5 on 2023-11-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_alter_manggota_no_hp_alter_manggota_no_telp_rumah_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manggota',
            table=None,
        ),
    ]
