# Generated by Django 4.2.5 on 2023-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstabungan',
            fields=[
                ('No_Rek_Tabungan', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Jenis_Tabungan', models.CharField(max_length=14)),
                ('Kode_Anggota', models.CharField(max_length=7)),
                ('Tanggal_Pembukaan_Rekening', models.DateField()),
                ('Jenis_Bunga', models.CharField(max_length=255)),
                ('Prosentase_Bunga', models.CharField(max_length=255)),
                ('Status_Aktif', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MsTabungan',
            },
        ),
    ]
